### ISSUE TITLE
composer timeout issue

### ISSUE THREAD

**Issue by midnightdee** [HDInnovations/UNIT3D-Installer#1]
snipped of the error:
Install stops after this happens.

============
su www-data -s /bin/bash --command="cd /var/www/html && laravel-echo-server client:add"
[============================] (Done!)
su www-data -s /bin/bash --command="cd /var/www/html && composer install -q"
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Please Wait ...)
In Process.php line 1258:
                                                                                                                                   
  The process "su www-data -s /bin/bash --command="cd /var/www/html && composer install -q"" exceeded the timeout of 900 seconds. 
=============

**Comment by babbittry** [comment]
I have the same problem.

`
su www-data -s /bin/bash --command="cd /var/www/html && npm install"
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Please Wait ...)
In Process.php line 1258:

  The process "su www-data -s /bin/bash --command="cd /var/www/html && npm install"" exceeded the timeout of 900 seconds.
`

**Comment by HDVinnie** [comment]
I have just tested the installer 4 times on a digital ocean droplet and cannot replicate. I will keep investigating this issue and will deploy a bandaid patch that may or may not solve the issue. Kind of hard to debug / fix when I cannot replicate the issue. We may also just build a new installer. It's probably time anyway.

**Comment by HDVinnie** [comment]
> Thank you @HDVinnie 
> 
> I'll try again later this evening and see if it works now.

Please lmk as only reports I can find in composer repo is it happening with certain hosts that have slow/congested networks sometimes.
