### ISSUE TITLE
mysql.service failed

### ISSUE THREAD

**Issue by colindaly** [HDInnovations/UNIT3D-Installer#3]
Running installer and stops when starting mysql service.

```
Job for mysql.service failed because the control process exited with error code.
See "systemctl status mysql.service" and "journalctl -xeu mysql.service" for details.
unit3d@host:/etc/mysql$ systemctl status mysql.service
× mysql.service - MySQL Community Server
     Loaded: loaded (/lib/systemd/system/mysql.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2023-11-10 05:16:28 UTC; 8s ago
    Process: 39269 ExecStartPre=/usr/share/mysql/mysql-systemd-start pre (code=exited, status=1/FA>
        CPU: 6ms

Nov 10 05:16:28 unit3d systemd[1]: mysql.service: Scheduled restart job, restart counter is at 5.
Nov 10 05:16:28 unit3d systemd[1]: Stopped MySQL Community Server.
Nov 10 05:16:28 unit3d systemd[1]: mysql.service: Start request repeated too quickly.
Nov 10 05:16:28 unit3d systemd[1]: mysql.service: Failed with result 'exit-code'.
Nov 10 05:16:28 unit3d systemd[1]: Failed to start MySQL Community Server.
```

Ran cmd `mysqld --verbose --help` and error reports...
```
mysqld: Can't read dir of '/etc/mysql/conf.d/' (OS errno 2 - No such file or directory)
mysqld: [ERROR] Stopped processing the 'includedir' directive in file /etc/mysql/my.cnf at line 40.
mysqld: [ERROR] Fatal error in defaults handling. Program aborted!
```

Ran cmd 'ls' on dir '/etc/mysql/' and directory list is
`FROZEN  my.cnf  mysql.conf.d`

**Comment by HDVinnie** [comment]
@colindaly what OS? I used installer 5 times yesterday and just twice now on clean Ubuntu 22.04 with nothing else and installer went perfect.

**Comment by colindaly** [comment]
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian

**Comment by HDVinnie** [comment]
> PRETTY_NAME="Ubuntu 22.04.3 LTS"
> NAME="Ubuntu"
> VERSION_ID="22.04"
> VERSION="22.04.3 LTS (Jammy Jellyfish)"
> VERSION_CODENAME=jammy
> ID=ubuntu
> ID_LIKE=debian

I would suggest format and try again? I just tested it again with no issue. I cannot replicate your issue.

**Comment by colindaly** [comment]
Confirming a full disk format and Ubuntu 22.04 reinstall has resolved the issue. Thank you.
