### ISSUE TITLE
redis-server doesn't start automatically after reboot

### ISSUE THREAD

**Issue by gareth41** [HDInnovations/UNIT3D-Installer#4]
Ubuntu Server 22.04.3 LTS on VMWare

Ran fresh install of Ubuntu, cloned this repo and ran sudo ./install.sh

Everything works fine until the server is rebooted.  After reboot, redis-server doesn't start because the service isn't enabled.

Need to enable it with:
sudo systemctl enable redis-server

Everything works fine after that with no problems.

**Comment by HDVinnie** [comment]
fixed in v1.1.0
