### ISSUE TITLE
install comes with error

### ISSUE THREAD

**Issue by Lolles1911** [HDInnovations/UNIT3D-Installer#7]
Hey there.
tried several times to install version 8.0

each time it comes with 2 warnings:

Setting Up Web Site
================================================= ==============================

chown -R www-data:www-data /var/www/html/laravel-echo-server.json
[=░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
supervisorctl reread
[============================] (Done!)
supervisorctl update
[============================] (Done!)
supervisorctl reload
[============================] (Done!)
su www-data -s /bin/bash --command="cd /var/www/html && laravel-echo-server client:add"
[============================] (Done!)
su www-data -s /bin/bash --command="cd /var/www/html && composer install -q"
[=░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
su www-data -s /bin/bash --command="cd /var/www/html && bun install"
[============================] (Done!)
**[Warning] bash: bun: command not found**

su www-data -s /bin/bash --command="cd /var/www/html && bun run build"
[============================] (Done!)
**[Warning] bash: bun: command not found**

su www-data -s /bin/bash --command="cd /var/www/html && php artisan key:generate"
[============================] (Done!)
su www-data -s /bin/bash --command="cd /var/www/html && php artisan migrate --seed"
[============================] (Done!)
su www-data -s /bin/bash --command="cd /var/www/html && php artisan test:email"
[============================] (Done!)
[OK] Done!

================================================= ==============================
     Finalizing Install

Tried with 2 different machines.
have tried with
Ubuntu 22.04 LTS (Jammy Jellyfish)
Ubuntu 20.04 LTS (Focal Fossa)
with the same result.

it is a fresh install

**Comment by HDVinnie** [comment]
This is a valid issue. Will be fixed asap. In meantime can just run `bun install && bun run build` after installer completes.

**Comment by HDVinnie** [comment]
@Lolles1911 this is fixed in v1.2.2. You can reformat your server if wish and start install from scratch.
